import os

DEMO_MODE = os.environ.get("DEMO_MODE", "0") == "1"
AUTO_DOWNLOAD_MODELS = os.environ.get("AUTO_DOWNLOAD_MODELS", "1") == "1"

CAMERA_INDEX = int(os.environ.get("CAMERA_INDEX", "0"))
FRAME_WIDTH = int(os.environ.get("FRAME_WIDTH", "640"))
FRAME_HEIGHT = int(os.environ.get("FRAME_HEIGHT", "480"))
TARGET_FPS = int(os.environ.get("TARGET_FPS", "30"))
STREAM_FPS = int(os.environ.get("STREAM_FPS", "15"))

CORS_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CORS_ORIGINS",
        "http://127.0.0.1:5173,http://localhost:5173",
    ).split(",")
    if origin.strip()
]

HEAD_TILT_WARNING_DEGREES = 8.0
HEAD_TILT_BAD_DEGREES = 15.0

SHOULDER_ALIGNMENT_WARNING_DEGREES = 5.0
SHOULDER_ALIGNMENT_BAD_DEGREES = 10.0

NECK_OFFSET_WARNING = 0.15
NECK_OFFSET_BAD = 0.30

FORWARD_HEAD_WARNING = 0.6
FORWARD_HEAD_BAD = 0.8

GAZE_WARNING_DEGREES = 15.0
GAZE_BAD_DEGREES = 25.0

TORSO_LEAN_WARNING_DEGREES = 8.0
TORSO_LEAN_BAD_DEGREES = 15.0

SLOUCH_WARNING = 0.35
SLOUCH_BAD = 0.70

SCORE_GOOD_THRESHOLD = 70
SCORE_WARNING_THRESHOLD = 40

SMOOTHING_ALPHA = 0.22

WARNING_FRAMES_BEFORE_ESCALATION = 30
BAD_FRAMES_BEFORE_ESCALATION = 60

SCORE_WEIGHT_HEAD_TILT = 20
SCORE_WEIGHT_SHOULDER = 15
SCORE_WEIGHT_NECK_OFFSET = 15
SCORE_WEIGHT_FORWARD_HEAD = 20
SCORE_WEIGHT_GAZE = 5
SCORE_WEIGHT_TORSO_LEAN = 0
SCORE_WEIGHT_SLOUCH = 25

MAX_MEASUREMENT_HISTORY = 300

WEBSOCKET_UPDATE_INTERVAL = 0.08
